repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-docstring-first
          - id: trailing-whitespace
          - id: check-yaml
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
