repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-docstring-first
          - id: trailing-whitespace
          - id: check-yaml
    - repo: https://github.com/psf/black
      rev: 21.11b1
      hooks:
          - id: black
