name: CI

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                python: ['3.8', '3.9', '3.10', '3.11', '3.12']
                os: [windows-latest, ubuntu-20.04, macos-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install the Python Dependencies
              run: pip install tox

            - name: Run Tox for ${{ matrix.python }}
              run: tox -e py

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
