name: Pipeline

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: windows-latest

        strategy:
            matrix:
                python: [3.8]

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install the Python Dependencies
              run: pip install tox

            - name: Run Tox
              run: tox -e py

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
